/**
 * PageSpeed Analyzer Pro — Report Generator (utils/reportGenerator.js)
 *
 * Transforms raw analysis payload into:
 *  - Structured JSON report
 *  - Plain-text summary
 *  - Triggers download of JSON or text report
 */

'use strict';

// ── Report structure builder ──────────────────────────────────────────────────

/**
 * Builds a clean, portable report object from analysis payload.
 * @param {object} payload  Raw analysis result from analyzer.js
 * @returns {object}
 */
export function buildReport(payload) {
  if (!payload) return null;

  return {
    meta: {
      generator:   'PageSpeed Analyzer Pro v1.0.0',
      analyzedAt:  new Date(payload.timestamp).toISOString(),
      url:         payload.url,
      title:       payload.title,
    },
    score:           payload.score,
    grade:           scoreToGrade(payload.score),

    metrics: {
      fcp:  { value: payload.metrics?.fcp,  rating: payload.metricRatings?.fcp  },
      lcp:  { value: payload.metrics?.lcp,  rating: payload.metricRatings?.lcp  },
      cls:  { value: payload.metrics?.cls,  rating: payload.metricRatings?.cls  },
      fid:  { value: payload.metrics?.fid,  rating: payload.metricRatings?.fid  },
      ttfb: { value: payload.metrics?.ttfb, rating: payload.metricRatings?.ttfb },
      tbt:  { value: payload.metrics?.tbt,  rating: payload.metricRatings?.tbt  },
      tti:  { value: payload.metrics?.tti,  rating: payload.metricRatings?.tti  },
    },

    resources: payload.resources,
    seo:       payload.seo,
    bestPractices: payload.bestPractices,

    suggestions: (payload.suggestions ?? []).map((s) => ({
      category:    s.category,
      impact:      s.impact,
      title:       s.title,
      description: s.description,
      fix:         s.fix,
    })),

    summary: buildTextSummary(payload),
  };
}

// ── Grade helper ──────────────────────────────────────────────────────────────

function scoreToGrade(score) {
  if (score === null || score === undefined) return 'N/A';
  if (score >= 90) return 'A';
  if (score >= 80) return 'B';
  if (score >= 70) return 'C';
  if (score >= 60) return 'D';
  return 'F';
}

// ── Text summary ──────────────────────────────────────────────────────────────

function buildTextSummary(payload) {
  const lines = [];
  lines.push(`PageSpeed Analyzer Pro — Report`);
  lines.push(`URL: ${payload.url}`);
  lines.push(`Analysed: ${new Date(payload.timestamp).toLocaleString()}`);
  lines.push(`Score: ${payload.score ?? 'N/A'}/100 (${scoreToGrade(payload.score)})`);
  lines.push('');
  lines.push('── Core Web Vitals ──');

  const m = payload.metrics ?? {};
  const r = payload.metricRatings ?? {};

  lines.push(`FCP:  ${m.fcp  != null ? m.fcp  + 'ms' : '—'} [${r.fcp  ?? '?'}]`);
  lines.push(`LCP:  ${m.lcp  != null ? m.lcp  + 'ms' : '—'} [${r.lcp  ?? '?'}]`);
  lines.push(`CLS:  ${m.cls  != null ? m.cls.toFixed(3) : '—'} [${r.cls  ?? '?'}]`);
  lines.push(`FID:  ${m.fid  != null ? m.fid  + 'ms' : '—'} [${r.fid  ?? '?'}]`);
  lines.push(`TTFB: ${m.ttfb != null ? m.ttfb + 'ms' : '—'} [${r.ttfb ?? '?'}]`);
  lines.push(`TBT:  ${m.tbt  != null ? m.tbt  + 'ms' : '—'} [${r.tbt  ?? '?'}]`);
  lines.push(`TTI:  ${m.tti  != null ? m.tti  + 'ms' : '—'} [${r.tti  ?? '?'}]`);
  lines.push('');
  lines.push('── Top Suggestions ──');

  const sug = (payload.suggestions ?? []).slice(0, 10);
  sug.forEach((s, i) => {
    lines.push(`${i + 1}. [${s.impact.toUpperCase()}] ${s.title}`);
    lines.push(`   ${s.description.slice(0, 120)}...`);
  });

  lines.push('');
  lines.push(`Generated by PageSpeed Analyzer Pro`);

  return lines.join('\n');
}

// ── Download helpers ──────────────────────────────────────────────────────────

/**
 * Download a file in the browser using a Blob URL.
 * @param {string} filename
 * @param {string} content
 * @param {string} mimeType
 */
export function downloadFile(filename, content, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke after a short delay to allow the download to start
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

/**
 * Export analysis result as JSON file.
 * @param {object} payload
 */
export function exportJSON(payload) {
  const report   = buildReport(payload);
  const content  = JSON.stringify(report, null, 2);
  const hostname = new URL(payload.url).hostname.replace(/[^a-z0-9]/gi, '-');
  const date     = new Date().toISOString().slice(0, 10);
  downloadFile(`psa-report-${hostname}-${date}.json`, content, 'application/json');
}

/**
 * Export analysis result as plain text file.
 * @param {object} payload
 */
export function exportText(payload) {
  const report   = buildReport(payload);
  const hostname = new URL(payload.url).hostname.replace(/[^a-z0-9]/gi, '-');
  const date     = new Date().toISOString().slice(0, 10);
  downloadFile(`psa-report-${hostname}-${date}.txt`, report.summary, 'text/plain');
}
