// ============================================
// GITIGNORE PREMIUM - ENTERPRISE EDITION v2.0.0
// ============================================

'use strict';

// ============================================
// PREMIUM TEMPLATE LIBRARY - 50+ TECHNOLOGIES
// ============================================

const PREMIUM_TEMPLATES = {
  // ===== NODE.JS ECOSYSTEM =====
  node: `# Node.js Premium Template
# Generated by GitIgnore Premium Enterprise

# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
.env.*.local

# Build outputs
dist/
build/
out/
.next/
.nuxt/
.cache/
.parcel-cache/

# IDE
.idea/
.vscode/
*.swp
*.swo
*~
.DS_Store

# Testing
coverage/
.nyc_output/
.nycrc
jest.config.js

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*`,

  npm: `# NPM Specific
package-lock.json
.npmrc
npm-debug.log*`,

  yarn: `# Yarn Specific
yarn.lock
.yarn/
.yarnrc.yml
.yarn/install-state.gz
.yarn/build-state.yml`,

  pnpm: `# PNPM Specific
pnpm-lock.yaml
pnpm-workspace.yaml
.pnpm-store/
.pnpm-debug.log*`,

  // ===== PYTHON ECOSYSTEM =====
  python: `# Python Premium Template

# Byte-compiled files
__pycache__/
*.py[cod]
*$py.class

# Virtual environments
venv/
env/
.venv/
.env/
ENV/
env.bak/
venv.bak/
pythonenv*

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Installer logs
pip-log.txt
pip-delete-this-directory.txt
pip-wheel-metadata/

# Unit test / coverage
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Jupyter Notebook
.ipynb_checkpoints
*/.ipynb_checkpoints/*

# PyCharm
.idea/
*.iml

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre
.pyre/

# pytype
.pytype/

# Cython
*.so

# Profiles
.prof`,

  django: `# Django Specific
*.log
*.pot
*.pyc
__pycache__/
local_settings.py
db.sqlite3
db.sqlite3-journal
media/
static/
staticfiles/
*.mo
*.egg-info/
dist/
build/

# Django-stubs
.mypy_cache/
.pytest_cache/`,

  flask: `# Flask Specific
instance/
.webassets-cache
.env
.flaskenv
flask_session/`,

  fastapi: `# FastAPI Specific
__pycache__/
*.pyc
.env
.pytest_cache/
.coverage
htmlcov/
.python-version`,

  // ===== JAVASCRIPT FRAMEWORKS =====
  react: `# React Premium Template

# Dependencies
node_modules/
package-lock.json
yarn.lock
pnpm-lock.yaml

# Build outputs
build/
dist/
out/
*.tsbuildinfo

# Environment
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Testing
coverage/
.nyc_output/

# IDE
.vscode/
.idea/
*.swp
*.swo

# React specific
.pnp/
.pnp.js
.eslintcache
.opt-in
.opt-out`,

  next: `# Next.js Premium Template

# Next.js build
.next/
out/
.next/cache/
.next/standalone/
.next/server/
.next/static/

# Environment
.env*.local
.env*.development
.env*.production

# Analytics
.vercel/
.vercel_project.json
vercel.json

# Debug
next-env.d.ts
next.config.js.__ebak__

# Generated files
*.tsbuildinfo
tsconfig.tsbuildinfo`,

  vue: `# Vue.js Template
node_modules/
dist/
dist-ssr/
*.local
.env
.env.local
.env.*.local
.npmrc
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.DS_Store
.vuepress/dist/
.vuepress/cache/
.temp/
.cache/
.nyc_output
coverage
*.log`,

  angular: `# Angular Template
# dependencies
/node_modules

# output
/dist
/tmp
/out-tsc

# IDEs
.idea/
.project
.classpath
.c9/
*.launch
.settings/
*.sublime-workspace

# IDE - VSCode
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json

# misc
/.sass-cache
/connect.lock
/coverage
/libpeerconnection.log
npm-debug.log
yarn-error.log
testem.log
/typings

# System Files
.DS_Store
Thumbs.db`,

  svelte: `# Svelte Template
node_modules/
dist/
/build/
*.log
.DS_Store
.env
.env.local
.vercel
.output/
.svelte-kit/`,

  // ===== BACKEND TECHNOLOGIES =====
  java: `# Java Premium Template

# Compiled files
*.class
*.war
*.ear
*.nar

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle/
build/
!gradle-wrapper.jar
.gradletasknamecache
gradle-app.setting

# Eclipse
.project
.classpath
.settings/
bin/

# IntelliJ IDEA
.idea/
*.iml
*.iws
*.ipr
out/

# NetBeans
nbproject/
nb-configuration.xml
nbactions.xml

# VS Code
.vscode/

# Environment
.env
.env.local

# Logs
*.log
logs/`,

  spring: `# Spring Boot Specific
application-*.properties
application-*.yml
spring-pid
target/
build/
HELP.md
!.mvn/wrapper/maven-wrapper.jar
!**/src/main/**/target/
!**/src/test/**/target/

# STS
.apt_generated
.factorypath
.springBeans
.sts4-cache

# IntelliJ
*.iml
*.ipr
*.iws
.idea/

# NetBeans
/nbproject/private/
/nbbuild/
/dist/
/nbdist/
/.nb-gradle/

# VS Code
.vscode/
.factorypath`,

  php: `# PHP Premium Template

# Composer
vendor/
composer.lock
composer.phar

# IDE
.idea/
.vscode/
*.sublime-*
.project
.classpath
.settings/

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
storage/logs/*

# Cache
storage/framework/cache/
storage/framework/sessions/
storage/framework/views/
storage/framework/testing/

# WordPress
wp-content/uploads/
wp-content/upgrade/
wp-content/cache/
wp-config-local.php

# Laravel Homestead
Homestead.json
Homestead.yaml
.env.homestead

# PHPUnit
.phpunit.result.cache
.phpunit.cache/
coverage/
tests/_output/

# OS
.DS_Store
Thumbs.db`,

  laravel: `# Laravel Specific
.env
.env.*
Homestead.yaml
Homestead.json
npm-debug.log
yarn-error.log
/vendor
/node_modules
/public/storage
/storage/*.key
/storage/debugbar
/.idea
/.vscode
.phpunit.result.cache
.php_cs.cache
_hoverlad
Homestead.yaml
Homestead.json
.env.production`,

  go: `# Go Premium Template

# Binaries
/bin/
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out

# Dependency directories
vendor/
/vendor/

# Go modules
go.sum

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store

# Test binaries
*.test

# Output of the go coverage tool
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
go.work.sum`,

  rust: `# Rust Premium Template

# Generated by Cargo
/target/
**/*.rs.bk
Cargo.lock
**/target/

# MSVC Windows builds
*.pdb

# IDEs
.idea/
.vscode/
*.iml
*.swp
*.swo

# OS
.DS_Store

# RustRover
.idea/

# Environment
.env
.env.local

# Logs
*.log`,

  ruby: `# Ruby Template
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
.env

# Ignore Byebug command history file.
.byebug_history

# Specific to RubyMotion (use on RubyMotion projects)
.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/

# Documentation cache and generated files
/.yardoc/
/_yardoc/
/doc/
/rdoc/

# Environment normalization
/.bundle/
/vendor/bundle
/lib/bundler/man/

# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
.rvmrc`,

  rails: `# Rails Specific
*.rbc
capybara-*.html
.rspec
/log
/tmp
/db/*.sqlite3
/db/*.sqlite3-journal
/db/*.sqlite3-*
/public/system
/public/assets
/coverage
/spec/tmp
**.orig
rerun.txt
pickle-email-*.html

# Ignore all logfiles and tempfiles.
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

# TODO Comment out this rule if environment variables can be committed
.env
.env.local

# Added by cargo
/target/

# Ignore JetBrains IDEs
.idea/`,

  // ===== DEVOPS & CLOUD =====
  docker: `# Docker Premium Template

# Docker files
docker-compose.override.yml
Dockerfile.local
Dockerfile.dev
.env
.env.local
.dockerignore

# Docker volumes
data/
volumes/
.docker-volumes/

# Docker Compose
docker-compose.override.yml
docker-compose.dev.yml
docker-compose.prod.yml

# Kubernetes
k8s/
*.kubeconfig

# Container registries
.dockercfg
.docker/config.json

# Logs
*.log
container-logs/`,

  kubernetes: `# Kubernetes Specific
*.kubeconfig
*.kubectx
helm/secrets/
helm/charts/*.tgz
helm/repositories.yaml
.kube/
aks-engine/
terraform.tfstate
terraform.tfstate.backup
.terraform/
*.plan
*.auto.tfvars
*.tfvars
!example.tfvars
.helm/
secrets.yaml
values.production.yaml
production.yaml`,

  terraform: `# Terraform Specific
*.tfstate
*.tfstate.*
.terraform/
.terraform.lock.hcl
terraform.tfvars
terraform.tfvars.json
*.auto.tfvars
*.auto.tfvars.json
crash.log
crash.*.log
override.tf
override.tf.json
_override.tf
_override.tf.json
terraform.rc
.terraformrc
plan.out
plan.tfplan`,

  ansible: `# Ansible Specific
*.retry
ansible.cfg
hosts
.ansible/
.vault_pass
vault_pass
vault_password_file
*.vault
inventory
inventory/*`,

  // ===== MOBILE DEVELOPMENT =====
  android: `# Android Premium Template

# Built application files
*.apk
*.aar
*.ap_
*.dex

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/
release/

# Gradle files
.gradle/
build/
*/build/
gradle-app.setting
!gradle-wrapper.jar

# IntelliJ IDEA
.idea/
*.iml
*.iws
*.ipr
out/

# Eclipse
.project
.classpath
.settings/
bin/
gen/
local.properties

# VS Code
.vscode/

# NDK
obj/
.externalNativeBuild

# OS
.DS_Store

# Environment
.env
.env.local
google-services.json
*.keystore
*.jks`,

  ios: `# iOS Premium Template

# Xcode
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata/
*.xccheckout
*.xcscmblueprint
*.xcscheme
!default.xcscheme
xcshareddata/
*.moved-aside
DerivedData/
.idea/
*.hmap
*.ipa
*.dSYM.zip
*.dSYM

# CocoaPods
Pods/
Podfile.lock
*.xcworkspace
!default.xcworkspace

# Carthage
Carthage/
Carthage/Build

# Swift Package Manager
.swiftpm/
.build/
Packages/
*.swiftsourceinfo
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.swiftpm/xcode/xcuserdata/

# Fastlane
fastlane/report.xml
fastlane/test_output
fastlane/Preview.html
fastlane/screenshots/**/*.png
fastlane/test_output

# Environment
.env
.env.local

# OS
.DS_Store`,

  flutter: `# Flutter Premium Template

# Flutter/Dart
.dart_tool/
.packages
build/
.flutter-plugins
.flutter-plugins-dependencies
.dart_tool/package_config.json
**/doc/api/
.dartdoc/
**/ios/Flutter/.last_build_id
**/ios/Flutter/App.framework
**/ios/Flutter/Flutter.framework
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/app.flx
**/ios/Flutter/app.zip
**/ios/Flutter/flutter_assets
**/ios/ServiceDefinitions.json
**/ios/Runner/GeneratedPluginRegistrant.*

# Android/OSX
**/android/**/gradle-wrapper.jar
**/android/.gradle
**/android/captures/
**/android/gradlew
**/android/gradlew.bat
**/android/local.properties
**/ios/**/Icon?
**/ios/**/Icon-*.png
**/ios/**/_Icon??
**/ios/**/xcuserdata

# Coverage
coverage/
*.g.dart
*.freezed.dart
*.mocks.dart

# IDE
.idea/
.vscode/
*.iml
*.swp
*.swo

# Environment
.env
.env.local

# Logs
*.log
flutter.log`,

  'react-native': `# React Native Premium Template

# Node
node_modules/
npm-debug.log
yarn-error.log

# iOS
**/ios/build/
**/ios/Pods/
**/ios/*.xcworkspace/
**/ios/*.xcodeproj/xcuserdata/
**/ios/*.xcodeproj/project.xcworkspace/
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/flutter_export_environment.sh

# Android
**/android/build/
**/android/app/build/
**/android/.gradle/
**/android/local.properties
**/android/**/gradle-wrapper.jar

# Environment
.env
.env.local
.env.*.local

# Watchman
.watchmanconfig

# Bundler
.bundle/

# Debug
*.log

# Metro
metro.config.js
.temp/

# IDE
.idea/
.vscode/
*.iml
*.swp
*.swo

# OS
.DS_Store`,

  // ===== CMS =====
  wordpress: `# WordPress Premium Template

# WordPress core
/wp-admin/
/wp-includes/
/wp-content/uploads/
/wp-content/upgrade/
/wp-content/cache/
/wp-content/backup-db/
/wp-content/plugins/
/wp-content/themes/
/wp-config.php

# Environment
.env
.env.local
wp-config-local.php
wp-config.php.bak

# Logs
/wp-content/debug.log
*.log

# IDEs
.idea/
.vscode/
*.sublime-*

# OS
.DS_Store
Thumbs.db

# Composer
vendor/
composer.lock
composer.phar

# Node
node_modules/
package-lock.json`,

  drupal: `# Drupal Specific
sites/*/files/
sites/*/private/
sites/*/settings.local.php
sites/sites.php
config/sync/
web/sites/*/files/
web/sites/*/private/
web/sites/*/settings.local.php
web/sites/sites.php
web/config/sync/
vendor/
composer.lock
node_modules/
.htaccess
/.env
/.env.local
/.idea/
/.vscode/
.DS_Store`,

  shopify: `# Shopify Specific
.shopify/
tmp/
*.log
.env
.env.local
config.yml
config/settings_data.json
config/settings_schema.json
node_modules/
package-lock.json
yarn.lock
.DS_Store
.idea/
.vscode/`,

  // ===== DATABASES =====
  mysql: `# MySQL Specific
*.sql
*.sql.gz
*.sql.zip
*.sql.7z
my.cnf
my.ini
.mysql_history
.mysqlsh/
data/
*.ibd
*.frm
*.myd
*.myi
*.opt`,

  postgresql: `# PostgreSQL Specific
*.sql
*.sql.gz
*.sql.zip
*.backup
*.dump
*.pgsql
postgresql.conf
pg_hba.conf
pg_ident.conf
postmaster.pid
postmaster.opts
pg_log/
pg_stat/
pg_stat_tmp/
pg_replslot/
pg_snapshots/
pg_wal/
pg_xlog/
postgresql.auto.conf`,

  mongodb: `# MongoDB Specific
*.bson
*.mongodb
*.mongodump
mongod.conf
mongod.log
mongodb.log
*.lock
storage/
journal/
mongod.lock
*.wt
WiredTiger*
diagnostic.data/`,

  // ===== DEPLOYMENT PLATFORMS =====
  aws: `# AWS Premium Template

# AWS SAM
.aws-sam/
samconfig.toml
samconfig.yaml
.template.yaml
*.template.yaml
*.sam.yaml

# CloudFormation
*.template
*.stack-outputs

# Terraform
*.tfstate
*.tfstate.*
.terraform/
terraform.tfvars

# CDK
cdk.out/
.cdk.staging/

# Beanstalk
.elasticbeanstalk/
*.ebextensions/

# Lambda
lambda.zip
*.lambda.zip

# Environment
.env
.env.local
.env.production

# Credentials
.aws/credentials
.aws/config`,

  azure: `# Azure Specific
.vs/
.vscode/
bin/
obj/
*.user
*.suo
*.userprefs
appsettings.Development.json
appsettings.Production.json
secrets.json
Properties/serviceDependencies.json
Properties/serviceDependencies.*.json
Properties/PublishProfiles/
Properties/launchSettings.json
.env
.env.local`,

  gcp: `# Google Cloud Specific
*.key.json
*.json.key
*.p12
*.pem
*.pfx
app.yaml
*.gcp.yaml
cloudbuild.yaml
.env
.env.local
.credentials/
.gcloud/
.gke/
.terraform/
*.tfstate
*.tfstate.*`,

  vercel: `# Vercel Specific
.vercel/
.vercel_project.json
vercel.json
.next/
.next/cache/
.next/standalone/
out/
build/
.env.*.local
.env.local
.env.production.local`,

  netlify: `# Netlify Specific
.netlify/
.netlify/state.json
functions/
.netlify/functions/
.netlify/build/
dist/
build/
.env
.env.*
.env.local
.env.production
.env.development
*.log
.netlify/deploy.log`,

  github: `# GitHub Pages Specific
_site/
.sass-cache/
.jekyll-cache/
.jekyll-metadata
vendor/bundle/
vendor/cache/
.github/
docs/_site/
docs/.sass-cache/
*.gem
Gemfile.lock
node_modules/
package-lock.json
yarn.lock
.env
.env.local`,

  firebase: `# Firebase Specific
.firebase/
firebase-debug.log
firebase-debug.*.log
*.cache
.firebaserc
firebase.json
database.rules.json
storage.rules
firestore.indexes.json
firestore.rules
.env
.env.local
.env.production
.env.staging
dist/
build/
.firebase/hosting.*.cache`,

  heroku: `# Heroku Specific
.heroku/
vendor/plugins/*
Procfile
app.json
.env
.env.local
.env.production
*.log
logs/*
tmp/*
!tmp/.keep
/public/assets
.heroku/netrc
.heroku/client.json`,

  general: `# Common Ignore Patterns
# OS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
*.lnk
desktop.ini
$RECYCLE.BIN/

# Editor
*.swp
*.swo
*~
.idea/
.vscode/
*.sublime-*
.project
.classpath
.settings/
*.iml
*.ipr
*.iws

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
logs/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Backup
*.bak
*.backup
*.orig

# Temp
tmp/
temp/
*.tmp
*.temp
.cache/

# Archive
*.zip
*.tar.gz
*.rar
*.7z
*.dmg

# Tests
coverage/
.nyc_output/
.hypothesis/
.pytest_cache/
.coverage
.tox/

# Misc
*.pid
*.seed
*.pid.lock
*.class
*.jar
*.war
*.ear`
};

// ============================================
// PREMIUM UTILITIES
// ============================================

class GitIgnorePremium {
  constructor() {
    this.initializeElements();
    this.attachEventListeners();
    this.updateWordCount = this.debounce(this.updateWordCount.bind(this), 300);
    this.init();
    
  }

    initializeElements() {
    this.elements = {
      techSelect: document.getElementById('techSelect'),
      platformSelect: document.getElementById('platformSelect'),
      generateBtn: document.getElementById('generateBtn'),
      autoDetectBtn: document.getElementById('autoDetectBtn'),
      clearBtn: document.getElementById('clearBtn'),
      copyBtn: document.getElementById('copyBtn'),
      downloadBtn: document.getElementById('downloadBtn'),
      output: document.getElementById('output'),
      gitignoreContent: document.getElementById('gitignoreContent'),
      wordCount: document.getElementById('wordCount'),
      selectedCount: document.getElementById('selectedCount')
    };

    // Validate required elements
    Object.entries(this.elements).forEach(([key, element]) => {
      if (!element) {
        console.error(`[GitIgnore Premium] Missing element: ${key}`);
      }
    });
  }

    initWideScreen() {
    console.log('[GitIgnore Premium] Initializing wide screen features');
    this.setupWideScreenFeatures();
    this.updateSelectedCount();
    this.setupQuickActions();
  }

  setupWideScreenFeatures() {
    if (this.elements.techSelect) {
      this.elements.techSelect.addEventListener('change', () => this.updateSelectedCount());
    }
  }
  
    updateSelectedCount() {
    const selectedCount = this.elements.selectedCount;
    if (!selectedCount) return;
    
    const selected = this.getSelectedTechs().length;
    selectedCount.textContent = selected;
    selectedCount.style.color = selected > 0 ? 'var(--premium-cyan)' : 'var(--premium-silver)';
  }

  setupQuickActions() {
    const quickActions = {
      quickNodeBtn: 'node',
      quickPythonBtn: 'python',
      quickReactBtn: 'react',
      quickDockerBtn: 'docker',
      quickJavaBtn: 'java'
    };
    
    Object.entries(quickActions).forEach(([btnId, techValue]) => {
      const btn = document.getElementById(btnId);
      if (btn) {
        btn.addEventListener('click', () => {
          if (this.elements.techSelect) {
            Array.from(this.elements.techSelect.options).forEach(opt => opt.selected = false);
            Array.from(this.elements.techSelect.options).forEach(opt => {
              if (opt.value === techValue) opt.selected = true;
            });
            this.updateSelectedCount();
            this.showNotification(`✅ Selected: ${techValue}`, 'success');
          }
        });
      }
    });
  }

  attachEventListeners() {
    if (this.elements.generateBtn) {
      this.elements.generateBtn.addEventListener('click', () => this.generateGitignore());
    }
    
    if (this.elements.autoDetectBtn) {
      this.elements.autoDetectBtn.addEventListener('click', () => this.autoDetectTech());
    }
    
    if (this.elements.clearBtn) {
      this.elements.clearBtn.addEventListener('click', () => this.clearSelection());
    }
    
    if (this.elements.copyBtn) {
      this.elements.copyBtn.addEventListener('click', () => this.copyToClipboard());
    }
    
    if (this.elements.downloadBtn) {
      this.elements.downloadBtn.addEventListener('click', () => this.downloadGitignore());
    }
    
    if (this.elements.gitignoreContent) {
      this.elements.gitignoreContent.addEventListener('input', () => this.updateWordCount());
    }

    // Keyboard shortcuts
    document.addEventListener('keydown', (e) => this.handleKeyboardShortcuts(e));
  }

  async init() {
    await this.loadStoredPreferences();
    if (typeof this.initWideScreen === 'function') {
      this.initWideScreen();
    } else {
      console.warn('[GitIgnore Premium] initWideScreen not found, using fallback');
      this.setupWideScreenFeatures();
      this.updateSelectedCount();
      this.setupQuickActions();
    }
  }

  async loadStoredPreferences() {
    try {
      const result = await chrome.storage.local.get(['lastTechs', 'lastPlatform']);
      
      if (result.lastTechs && this.elements.techSelect) {
        Array.from(this.elements.techSelect.options).forEach(option => {
          option.selected = result.lastTechs.includes(option.value);
        });
      }
      
      if (result.lastPlatform && this.elements.platformSelect) {
        this.elements.platformSelect.value = result.lastPlatform;
      }
    } catch (error) {
      console.error('[GitIgnore Premium] Error loading preferences:', error);
    }
  }

  async savePreferences() {
    try {
      const selectedTechs = this.getSelectedTechs();
      const platform = this.elements.platformSelect?.value || 'general';
      
      await chrome.storage.local.set({
        lastTechs: selectedTechs,
        lastPlatform: platform
      });
    } catch (error) {
      console.error('[GitIgnore Premium] Error saving preferences:', error);
    }
  }

  getSelectedTechs() {
    if (!this.elements.techSelect) return [];
    return Array.from(this.elements.techSelect.selectedOptions)
      .map(opt => opt.value);
  }

  generateGitignore() {
    const selectedTechs = this.getSelectedTechs();
    const platform = this.elements.platformSelect?.value || 'general';
    
    if (selectedTechs.length === 0) {
      this.showNotification('Please select at least one technology', 'warning');
      return;
    }

    let content = `# ===========================================\n`;
    content += `# .gitignore PREMIUM - Enterprise Edition\n`;
    content += `# Generated: ${new Date().toLocaleString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false 
    })}\n`;
    content += `# Technologies: ${selectedTechs.join(', ')}\n`;
    content += `# Platform: ${this.getPlatformName(platform)}\n`;
    content += `# ===========================================\n\n`;
    
    // Add technology-specific templates
    selectedTechs.forEach(tech => {
      if (PREMIUM_TEMPLATES[tech]) {
        content += PREMIUM_TEMPLATES[tech] + '\n\n';
      }
    });
    
    // Add platform-specific templates (if not already included)
    if (platform !== 'general' && PREMIUM_TEMPLATES[platform] && !selectedTechs.includes(platform)) {
      content += PREMIUM_TEMPLATES[platform] + '\n\n';
    }
    
    // Always add general ignores
    if (PREMIUM_TEMPLATES.general) {
      content += PREMIUM_TEMPLATES.general + '\n\n';
    }
    
    // Add footer
    content += `# ===========================================\n`;
    content += `# Generated with GitIgnore Premium Enterprise\n`;
    content += `# ===========================================\n`;
    
    if (this.elements.gitignoreContent) {
      this.elements.gitignoreContent.value = content.trim();
    }
    
    if (this.elements.output) {
      this.elements.output.style.display = 'block';
      this.elements.output.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
    
    this.updateWordCount();
    this.savePreferences();
    this.showNotification(`✨ Premium .gitignore generated! (${selectedTechs.length} technologies)`);
    this.updateSelectedCount();
  }

  getPlatformName(platform) {
    const platformNames = {
      general: 'General Purpose',
      aws: 'AWS',
      azure: 'Azure',
      gcp: 'Google Cloud',
      vercel: 'Vercel',
      netlify: 'Netlify',
      github: 'GitHub Pages',
      firebase: 'Firebase',
      heroku: 'Heroku'
    };
    return platformNames[platform] || platform.charAt(0).toUpperCase() + platform.slice(1);
  }

  updateWordCount() {
    if (!this.elements.gitignoreContent || !this.elements.wordCount) return;
    
    const content = this.elements.gitignoreContent.value;
    const lines = content.split('\n').filter(line => line.trim() !== '').length;
    const totalLines = content.split('\n').length;
    
    this.elements.wordCount.textContent = `${lines} rules • ${totalLines} lines`;
  }

  async copyToClipboard() {
    if (!this.elements.gitignoreContent || !this.elements.gitignoreContent.value.trim()) {
      this.showNotification('Nothing to copy! Generate content first.', 'warning');
      return;
    }

    try {
      await navigator.clipboard.writeText(this.elements.gitignoreContent.value);
      
      if (this.elements.copyBtn) {
        const originalHTML = this.elements.copyBtn.innerHTML;
        this.elements.copyBtn.innerHTML = '✓ Copied!';
        this.elements.copyBtn.style.background = 'linear-gradient(135deg, #47B5FF 0%, #1363DF 100%)';
        
        setTimeout(() => {
          if (this.elements.copyBtn) {
            this.elements.copyBtn.innerHTML = '📋 Copy';
            this.elements.copyBtn.style.background = '';
          }
        }, 2000);
      }
      
      this.showNotification('✓ .gitignore copied to clipboard');
    } catch (error) {
      // Fallback
      this.elements.gitignoreContent.select();
      document.execCommand('copy');
      this.showNotification('✓ .gitignore copied to clipboard');
    }
  }

  downloadGitignore() {
    if (!this.elements.gitignoreContent || !this.elements.gitignoreContent.value.trim()) {
      this.showNotification('Nothing to download! Generate content first.', 'warning');
      return;
    }

    const content = this.elements.gitignoreContent.value;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    
    a.href = url;
    a.download = '.gitignore';
    document.body.appendChild(a);
    a.click();
    
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
    
    this.showNotification('⬇️ .gitignore file downloaded');
  }

  async autoDetectTech() {
    if (!this.elements.autoDetectBtn) return;

    try {
      const originalText = this.elements.autoDetectBtn.innerHTML;
      this.elements.autoDetectBtn.innerHTML = '<span class="premium-loading"></span> Detecting...';
      this.elements.autoDetectBtn.disabled = true;

      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      
      if (tab.url.startsWith('chrome://') || tab.url.startsWith('chrome-extension://')) {
        this.showNotification('Auto-detect not available on this page', 'warning');
        return;
      }

      const detectedTechs = await chrome.runtime.sendMessage({ 
        action: 'detectTechStack', 
        tabId: tab.id 
      });

      if (detectedTechs && detectedTechs.length > 0) {
        if (this.elements.techSelect) {
          Array.from(this.elements.techSelect.options).forEach(option => {
            option.selected = detectedTechs.includes(option.value);
          });
        }
        
        this.showNotification(`🔍 Auto-detected: ${detectedTechs.join(', ')}`);
      } else {
        this.showNotification('No technologies detected on this page', 'warning');
      }
    } catch (error) {
      console.error('[GitIgnore Premium] Auto-detect error:', error);
      this.showNotification('Auto-detect failed', 'error');
    } finally {
      if (this.elements.autoDetectBtn) {
        this.elements.autoDetectBtn.innerHTML = '🔍 Auto-detect';
        this.elements.autoDetectBtn.disabled = false;
      }
    }
  }

  clearSelection() {
    if (this.elements.techSelect) {
      Array.from(this.elements.techSelect.options).forEach(option => option.selected = false);
    }
    
    if (this.elements.platformSelect) {
      this.elements.platformSelect.value = 'general';
    }
    
    if (this.elements.output) {
      this.elements.output.style.display = 'none';
    }
    
    if (this.elements.gitignoreContent) {
      this.elements.gitignoreContent.value = '';
    }
    
    this.showNotification('✓ Selection cleared');
  }

  handleKeyboardShortcuts(e) {
    // Ctrl/Cmd + Enter: Generate
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
      e.preventDefault();
      this.generateGitignore();
    }
    
    // Ctrl/Cmd + C: Copy (only when textarea focused)
    if ((e.ctrlKey || e.metaKey) && e.key === 'c' && 
        document.activeElement === this.elements.gitignoreContent) {
      e.preventDefault();
      this.copyToClipboard();
    }
    
    // Escape: Hide output
    if (e.key === 'Escape' && this.elements.output) {
      this.elements.output.style.display = 'none';
    }
  }

  showNotification(message, type = 'success') {
    // Remove existing notification
    const existing = document.querySelector('.premium-notification');
    if (existing) existing.remove();

    const notification = document.createElement('div');
    notification.className = `premium-notification ${type}`;
    notification.innerHTML = `
      <span>${message}</span>
      <button class="premium-notification-close" aria-label="Close">✕</button>
    `;

    document.body.appendChild(notification);

    // Auto-remove after 3 seconds
    const timeout = setTimeout(() => {
      if (notification.parentNode) {
        notification.style.animation = 'slideOut 0.3s ease';
        setTimeout(() => notification.remove(), 300);
      }
    }, 3000);

    // Manual close
    notification.querySelector('.premium-notification-close').addEventListener('click', () => {
      clearTimeout(timeout);
      notification.style.animation = 'slideOut 0.3s ease';
      setTimeout(() => notification.remove(), 300);
    });
  }

  debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
      const later = () => {
        clearTimeout(timeout);
        func(...args);
      };
      clearTimeout(timeout);
      timeout = setTimeout(later, wait);
    };
  }
}

// ============================================
// INITIALIZATION
// ============================================

// Ensure DOM is fully loaded
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    new GitIgnorePremium();
  });
} else {
  new GitIgnorePremium();
}